# Please don't edit this file, and use the version generated at
# http://rainboard.laas.fr/project/eigenpy/.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

.robotpkg-py-eigenpy: &robotpkg-py-eigenpy
  except:
    - gh-pages
  script:
    - mkdir -p ccache
    - cd /root/robotpkg/math
    - git pull
    - cd py-eigenpy
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    - make test

robotpkg-py-eigenpy-14.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:14.04

robotpkg-py-eigenpy-14.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:14.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf

robotpkg-py-eigenpy-py3-14.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:14.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf
  allow_failure: true

robotpkg-py-eigenpy-py3-14.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:14.04
  allow_failure: true

robotpkg-py-eigenpy-16.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:16.04

robotpkg-py-eigenpy-py3-16.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:16.04
  allow_failure: true

robotpkg-py-eigenpy-16.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:16.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf

robotpkg-py-eigenpy-py3-16.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:16.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf
  allow_failure: true

robotpkg-py-eigenpy-18.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:18.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf

robotpkg-py-eigenpy-py3-18.04-debug:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:18.04
  before_script:
    - echo PKG_OPTIONS.py-eigenpy=debug >> /opt/openrobots/etc/robotpkg.conf

robotpkg-py-eigenpy-py3-18.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy-py3:18.04

robotpkg-py-eigenpy-18.04-release:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:18.04

doc-coverage:
  <<: *robotpkg-py-eigenpy
  image: eur0c.laas.fr:5000/stack-of-tasks/eigenpy/py-eigenpy:16.04
  before_script:
    - echo -e 'CXXFLAGS+= --coverage\nLDFLAGS+= --coverage\nPKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
  after_script:
    - cd /root/robotpkg/math/py-eigenpy
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    - mkdir -p ${CI_PROJECT_DIR}/coverage/
    - gcovr -r .
    - gcovr -r . --html --html-details -o ${CI_PROJECT_DIR}/coverage/index.html
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
      - coverage/
